services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app:cached
    env_file:
      - .env
    command: tail -f /dev/null
    ports:
      - "5173:5173"
